# noinspection PyUnresolvedReferences
from pygame.event import *
import pygame


# Base
QUIT = pygame.QUIT
ACTIVEEVENT = pygame.ACTIVEEVENT
KEYDOWN = pygame.KEYDOWN
KEYUP = pygame.KEYUP
MOUSEMOTION = pygame.MOUSEMOTION
MOUSEBUTTONUP = pygame.MOUSEBUTTONUP
MOUSEBUTTONDOWN = pygame.MOUSEBUTTONDOWN
JOYAXISMOTION = pygame.JOYAXISMOTION
JOYBALLMOTION = pygame.JOYBALLMOTION
JOYHATMOTION = pygame.JOYHATMOTION
JOYBUTTONUP = pygame.JOYBUTTONUP
JOYBUTTONDOWN = pygame.JOYBUTTONDOWN
VIDEORESIZE = pygame.VIDEORESIZE
VIDEOEXPOSE = pygame.VIDEOEXPOSE
USEREVENT = pygame.USEREVENT

# SDL2
AUDIODEVICEADDED = pygame.AUDIODEVICEADDED
AUDIODEVICEREMOVED = pygame.AUDIODEVICEREMOVED
FINGERMOTION = pygame.FINGERMOTION
FINGERDOWN = pygame.FINGERDOWN
FINGERUP = pygame.FINGERUP
MOUSEWHEEL = pygame.MOUSEWHEEL
MULTIGESTURE = pygame.MULTIGESTURE
TEXTEDITING = pygame.TEXTEDITING
TEXTINPUT = pygame.TEXTINPUT

# Window Events
WINDOWCLOSE = pygame.WINDOWCLOSE
WINDOWENTER = pygame.WINDOWENTER
WINDOWEXPOSED = pygame.WINDOWEXPOSED
WINDOWFOCUSGAINED = pygame.WINDOWFOCUSGAINED
WINDOWFOCUSLOST = pygame.WINDOWFOCUSLOST
WINDOWHIDDEN = pygame.WINDOWHIDDEN
WINDOWHITTEST = pygame.WINDOWHITTEST
WINDOWLEAVE = pygame.WINDOWLEAVE
WINDOWMAXIMIZED = pygame.WINDOWMAXIMIZED
WINDOWMINIMIZED = pygame.WINDOWMINIMIZED
WINDOWMOVED = pygame.WINDOWMOVED
WINDOWRESIZED = pygame.WINDOWRESIZED
WINDOWRESTORED = pygame.WINDOWRESTORED
WINDOWSHOWN = pygame.WINDOWSHOWN
WINDOWSIZECHANGED = pygame.WINDOWSIZECHANGED
WINDOWTAKEFOCUS = pygame.WINDOWTAKEFOCUS

DROPBEGIN = pygame.DROPBEGIN
DROPCOMPLETE = pygame.DROPCOMPLETE
DROPFILE = pygame.DROPFILE
DROPTEXT = pygame.DROPTEXT

MIDIIN = pygame.MIDIIN
MIDIOUT = pygame.MIDIOUT

CONTROLLERDEVICEADDED = pygame.CONTROLLERDEVICEADDED
JOYDEVICEADDED = pygame.JOYDEVICEADDED
CONTROLLERDEVICEREMOVED = pygame.CONTROLLERDEVICEREMOVED
JOYDEVICEREMOVED = pygame.JOYDEVICEREMOVED
CONTROLLERDEVICEREMAPPED = pygame.CONTROLLERDEVICEREMAPPED

