# noinspection PyUnresolvedReferences
import pygame_gui
from pygame.event import *
import pygame


# Base
QUIT = pygame.QUIT
ACTIVEEVENT = pygame.ACTIVEEVENT
KEYDOWN = pygame.KEYDOWN
KEYUP = pygame.KEYUP
MOUSEMOTION = pygame.MOUSEMOTION
MOUSEBUTTONUP = pygame.MOUSEBUTTONUP
MOUSEBUTTONDOWN = pygame.MOUSEBUTTONDOWN
JOYAXISMOTION = pygame.JOYAXISMOTION
JOYBALLMOTION = pygame.JOYBALLMOTION
JOYHATMOTION = pygame.JOYHATMOTION
JOYBUTTONUP = pygame.JOYBUTTONUP
JOYBUTTONDOWN = pygame.JOYBUTTONDOWN
VIDEORESIZE = pygame.VIDEORESIZE
VIDEOEXPOSE = pygame.VIDEOEXPOSE
USEREVENT = pygame.USEREVENT

# SDL2
AUDIODEVICEADDED = pygame.AUDIODEVICEADDED
AUDIODEVICEREMOVED = pygame.AUDIODEVICEREMOVED
FINGERMOTION = pygame.FINGERMOTION
FINGERDOWN = pygame.FINGERDOWN
FINGERUP = pygame.FINGERUP
MOUSEWHEEL = pygame.MOUSEWHEEL
MULTIGESTURE = pygame.MULTIGESTURE
TEXTEDITING = pygame.TEXTEDITING
TEXTINPUT = pygame.TEXTINPUT

# Window Events
WINDOWCLOSE = pygame.WINDOWCLOSE
WINDOWENTER = pygame.WINDOWENTER
WINDOWEXPOSED = pygame.WINDOWEXPOSED
WINDOWFOCUSGAINED = pygame.WINDOWFOCUSGAINED
WINDOWFOCUSLOST = pygame.WINDOWFOCUSLOST
WINDOWHIDDEN = pygame.WINDOWHIDDEN
WINDOWHITTEST = pygame.WINDOWHITTEST
WINDOWLEAVE = pygame.WINDOWLEAVE
WINDOWMAXIMIZED = pygame.WINDOWMAXIMIZED
WINDOWMINIMIZED = pygame.WINDOWMINIMIZED
WINDOWMOVED = pygame.WINDOWMOVED
WINDOWRESIZED = pygame.WINDOWRESIZED
WINDOWRESTORED = pygame.WINDOWRESTORED
WINDOWSHOWN = pygame.WINDOWSHOWN
WINDOWSIZECHANGED = pygame.WINDOWSIZECHANGED
WINDOWTAKEFOCUS = pygame.WINDOWTAKEFOCUS

DROPBEGIN = pygame.DROPBEGIN
DROPCOMPLETE = pygame.DROPCOMPLETE
DROPFILE = pygame.DROPFILE
DROPTEXT = pygame.DROPTEXT

MIDIIN = pygame.MIDIIN
MIDIOUT = pygame.MIDIOUT

CONTROLLERDEVICEADDED = pygame.CONTROLLERDEVICEADDED
JOYDEVICEADDED = pygame.JOYDEVICEADDED
CONTROLLERDEVICEREMOVED = pygame.CONTROLLERDEVICEREMOVED
JOYDEVICEREMOVED = pygame.JOYDEVICEREMOVED
CONTROLLERDEVICEREMAPPED = pygame.CONTROLLERDEVICEREMAPPED

# UI (pygame_gui)

UI_BUTTON_PRESSED = pygame_gui.UI_BUTTON_PRESSED
UI_BUTTON_START_PRESS = pygame_gui.UI_BUTTON_START_PRESS
UI_BUTTON_DOUBLE_CLICKED = pygame_gui.UI_BUTTON_DOUBLE_CLICKED
UI_BUTTON_ON_HOVERED = pygame_gui.UI_BUTTON_ON_HOVERED
UI_BUTTON_ON_UNHOVERED = pygame_gui.UI_BUTTON_ON_UNHOVERED
UI_TEXT_BOX_LINK_CLICKED = pygame_gui.UI_TEXT_BOX_LINK_CLICKED
UI_TEXT_ENTRY_CHANGED = pygame_gui.UI_TEXT_ENTRY_CHANGED
UI_TEXT_ENTRY_FINISHED = pygame_gui.UI_TEXT_ENTRY_FINISHED
UI_DROP_DOWN_MENU_CHANGED = pygame_gui.UI_DROP_DOWN_MENU_CHANGED
UI_HORIZONTAL_SLIDER_MOVED = pygame_gui.UI_HORIZONTAL_SLIDER_MOVED
UI_SELECTION_LIST_NEW_SELECTION = pygame_gui.UI_SELECTION_LIST_NEW_SELECTION
UI_SELECTION_LIST_DROPPED_SELECTION = pygame_gui.UI_SELECTION_LIST_DROPPED_SELECTION
UI_SELECTION_LIST_DOUBLE_CLICKED_SELECTION = pygame_gui.UI_SELECTION_LIST_DOUBLE_CLICKED_SELECTION
UI_WINDOW_CLOSE = pygame_gui.UI_WINDOW_CLOSE
UI_WINDOW_MOVED_TO_FRONT = pygame_gui.UI_WINDOW_MOVED_TO_FRONT
UI_CONFIRMATION_DIALOG_CONFIRMED = pygame_gui.UI_CONFIRMATION_DIALOG_CONFIRMED
UI_FILE_DIALOG_PATH_PICKED = pygame_gui.UI_FILE_DIALOG_PATH_PICKED
UI_COLOUR_PICKER_COLOUR_PICKED = pygame_gui.UI_COLOUR_PICKER_COLOUR_PICKED
UI_COLOUR_PICKER_COLOUR_CHANNEL_CHANGED = pygame_gui.UI_COLOUR_PICKER_COLOUR_CHANNEL_CHANGED